"""
V1.2.6 — Agent Audit endpoints.

Exposes the line-by-line audit log generated by
/app/scripts/generate_agent_audit.sh. Admin-only.

Endpoints:
  GET  /api/audit/agent-log/summary    JSON  → totals, last 10 commits
  GET  /api/audit/agent-log            text  → full markdown audit
  GET  /api/audit/agent-log.json       JSON  → full machine-readable audit
  POST /api/audit/agent-log/regenerate JSON  → re-run the generator script

All endpoints require an authenticated admin/owner/creator JWT.
"""
import subprocess
from pathlib import Path
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import PlainTextResponse, JSONResponse
from deps import db, get_current_user

router = APIRouter(prefix="/audit", tags=["agent-audit"])

REPO_ROOT = Path("/app")
AUDIT_MD = REPO_ROOT / "AGENT_AUDIT_LINE_BY_LINE.md"
AUDIT_JSON = REPO_ROOT / "AGENT_AUDIT_LINE_BY_LINE.json"
GEN_SCRIPT = REPO_ROOT / "scripts" / "generate_agent_audit.sh"


async def _require_admin(user: dict = Depends(get_current_user)) -> dict:
    if not user:
        raise HTTPException(status_code=401, detail="Authentication required")
    doc = await db.users.find_one(
        {"id": user.get("id")},
        {"_id": 0, "role": 1, "is_admin": 1, "is_owner": 1, "tier": 1},
    ) or {}
    role = (doc.get("role") or "").lower()
    tier = (doc.get("tier") or "").lower()
    privileged = (
        role in ("admin", "creator", "owner", "architect")
        or tier in ("creator", "admin", "owner")
        or bool(doc.get("is_admin") or doc.get("is_owner"))
    )
    if not privileged:
        raise HTTPException(status_code=403, detail="Admin role required")
    return user


def _ensure_audit_exists() -> None:
    """Generate the audit on first request if missing."""
    if AUDIT_MD.exists() and AUDIT_JSON.exists():
        return
    if not GEN_SCRIPT.exists():
        raise HTTPException(status_code=500, detail="Audit generator script missing")
    try:
        subprocess.run(["bash", str(GEN_SCRIPT)], check=True, capture_output=True, timeout=60)
    except subprocess.CalledProcessError as e:
        raise HTTPException(status_code=500, detail=f"Audit generation failed: {e.stderr.decode()[:200]}")
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=500, detail="Audit generation timed out")


@router.get("/agent-log/summary")
async def audit_summary(_: dict = Depends(_require_admin)):
    """Quick stats: total commits, file size, last 10 commits."""
    _ensure_audit_exists()
    import json as _json
    data = _json.loads(AUDIT_JSON.read_text())
    commits = data.get("commits", [])
    return {
        "total_commits": data.get("total", len(commits)),
        "audit_md_bytes": AUDIT_MD.stat().st_size,
        "audit_json_bytes": AUDIT_JSON.stat().st_size,
        "last_10": [
            {
                "sha": c["sha"],
                "date": c["date"],
                "author": c["author"],
                "subject": c["subject"],
                "files_changed_count": c["file_count"],
                "lines_added": sum((f["lines_added"] or 0) for f in c["files_changed"]),
                "lines_removed": sum((f["lines_removed"] or 0) for f in c["files_changed"]),
            }
            for c in commits[:10]
        ],
    }


@router.get("/agent-log", response_class=PlainTextResponse)
async def audit_full_md(_: dict = Depends(_require_admin)):
    """Full human-readable markdown audit."""
    _ensure_audit_exists()
    return PlainTextResponse(AUDIT_MD.read_text(), media_type="text/markdown; charset=utf-8")


@router.get("/agent-log.json")
async def audit_full_json(_: dict = Depends(_require_admin)):
    """Full machine-readable audit (one record per commit)."""
    _ensure_audit_exists()
    import json as _json
    return JSONResponse(_json.loads(AUDIT_JSON.read_text()))


@router.post("/agent-log/regenerate")
async def audit_regenerate(_: dict = Depends(_require_admin)):
    """Force-regenerate the audit from current git history."""
    if not GEN_SCRIPT.exists():
        raise HTTPException(status_code=500, detail="Audit generator script missing")
    try:
        result = subprocess.run(
            ["bash", str(GEN_SCRIPT)],
            check=True, capture_output=True, timeout=60, text=True,
        )
        return {
            "ok": True,
            "stdout": result.stdout.strip().splitlines()[-5:],
            "audit_md_bytes": AUDIT_MD.stat().st_size,
            "audit_json_bytes": AUDIT_JSON.stat().st_size,
        }
    except subprocess.CalledProcessError as e:
        raise HTTPException(status_code=500, detail=f"Regenerate failed: {e.stderr[:200]}")
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=500, detail="Regenerate timed out")
