from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional
import sys
sys.path.insert(0, '/app/backend')
from engines.refractive_machine import get_machine

router = APIRouter(prefix="/machine", tags=["Refractive Machine"])


class DiagnosticRequest(BaseModel):
    sample_id: str
    administrator: Optional[str] = "Nicole Barlow"
    outer_resistance: Optional[float] = 0.998
    inner_resistance: Optional[float] = 0.998


class DecryptRequest(BaseModel):
    encrypted_payload: str
    barrier_key: str
    nonce: str
    tag: str
    refractive_index: Optional[float] = None
    status: Optional[str] = None


@router.post("/diagnostic")
async def run_diagnostic(request: DiagnosticRequest):
    """
    Run a full diagnostic with encrypted artifact generation.
    Combines dual-barrier refractive analysis with AES-256/RSA-2048 encryption.
    """
    machine = get_machine(request.administrator)
    artifact = machine.run_diagnostic(
        request.sample_id,
        outer_r=request.outer_resistance,
        inner_r=request.inner_resistance
    )
    return artifact


@router.post("/decrypt")
async def decrypt_artifact(request: DecryptRequest):
    """
    Decrypt an artifact using the machine's private key.
    Only works for artifacts generated by the same machine instance.
    """
    machine = get_machine()
    artifact = {
        "encrypted_payload": request.encrypted_payload,
        "barrier_key": request.barrier_key,
        "nonce": request.nonce,
        "tag": request.tag,
        "refractive_index": request.refractive_index,
        "status": request.status
    }
    result = machine.decrypt_artifact(artifact)
    
    if result.get("status") == "DECRYPTION_FAILED":
        raise HTTPException(status_code=400, detail=result)
    
    return result


@router.get("/public-key")
async def get_public_key():
    """
    Export the machine's public key for external artifact verification.
    """
    machine = get_machine()
    return {
        "public_key": machine.export_public_key(),
        "algorithm": "RSA-2048-OAEP",
        "inner_cipher": "AES-256-EAX"
    }


@router.get("/status")
async def machine_status():
    """
    Returns the current machine configuration.
    """
    machine = get_machine()
    return {
        "status": "active",
        "engine": "RefractiveMachine",
        "administrator": machine.admin,
        "phi_constant": machine.phi,
        "encryption": {
            "outer_barrier": "RSA-2048-OAEP",
            "inner_barrier": "AES-256-EAX"
        },
        "stability_threshold": 0.615
    }
