import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Shield, Database, Eye, Lock, Trash2, Mail, UserCheck } from 'lucide-react';

// Fixed lastUpdated date so builds don't churn the meta every deploy
const LAST_UPDATED = 'February 19, 2026';

export default function PrivacyPage() {
  const navigate = useNavigate();
  useEffect(() => { if (typeof window.__workAccrue === 'function') window.__workAccrue('privacy', 2); }, []);
  useEffect(() => { document.title = 'Privacy Policy · ENLIGHTEN.MINT.CAFE'; }, []);

  const sections = [
    {
      icon: Shield,
      title: 'Who We Are',
      color: '#C084FC',
      content: 'ENLIGHTEN.MINT.CAFE ("the App", "we", "us") is a wellness and spiritual practice platform operated under a Private Sovereign Trust by INFINITY SOVEREIGN. This Privacy Policy explains what information we collect, how we use it, and the rights you have over it.',
    },
    {
      icon: Database,
      title: 'Information We Collect',
      color: '#38BDF8',
      content: 'We collect only what is required to provide the service: (1) account data you give us (email, display name, hashed password); (2) in-app activity required for gamification (module visits, presence timers, Sparks/Dust balances, quest progress, equipped items); (3) device data automatically produced by your browser or the Android WebView (user-agent, approximate region from IP for localisation). We do NOT collect contacts, call logs, SMS, precise location, biometric data, health records, or any Special-Category data as defined under GDPR Art. 9.',
    },
    {
      icon: Eye,
      title: 'How We Use It',
      color: '#22C55E',
      content: 'Your data is used solely to (a) authenticate your account, (b) award and display your in-app progress (Sparks, Dust, Gaming Cards, 9×9 Crystalline Lattice resonance), (c) operate the Shareable Resonance Pattern (only when you explicitly press Share), and (d) diagnose errors via aggregated, non-identifying logs. We never profile you for advertising, never sell your data, and never use it to train external third-party AI models.',
    },
    {
      icon: Lock,
      title: 'How It Is Protected',
      color: '#E879F9',
      content: 'Passwords are hashed with bcrypt before storage. All transport uses HTTPS (TLS 1.2+). Databases run inside a private network with restricted credentials. Data integrity is maintained via the Crystal Seal framework using SHA-256. We use no deprecated hashing algorithms. Random values for the internal economy are generated by Python `secrets`.',
    },
    {
      icon: UserCheck,
      title: 'Third Parties',
      color: '#FB923C',
      content: 'We rely on a small, vetted set of processors: (1) MongoDB Atlas for storage, (2) OpenAI, Google (Gemini) and Anthropic LLM APIs for AI-generated text and imagery (prompts are transmitted, never your account identity), (3) SendGrid for transactional email (only when you request it). We do not integrate Facebook SDK, TikTok SDK, or any advertising SDK. No third-party trackers are embedded in the app.',
    },
    {
      icon: Trash2,
      title: 'Your Rights & Data Deletion',
      color: '#EF4444',
      content: 'You can request at any time: (i) a copy of all data we hold about you, (ii) correction of inaccuracies, (iii) full account deletion. To request deletion, email sovereign@enlighten.mint.cafe or open Settings → "Delete my account" in the app. Your account, associated wallet, quest log, and inventory are permanently removed within 14 days; backups purge within 30 days.',
    },
    {
      icon: Shield,
      title: 'Children',
      color: '#2DD4BF',
      content: 'The App is not directed to children under 13 (or under 16 where GDPR applies) and we do not knowingly collect their data. If we become aware that we have inadvertently collected personal data from a child, we will delete it promptly.',
    },
    {
      icon: Mail,
      title: 'Contact',
      color: '#A78BFA',
      content: 'Privacy enquiries, access requests, or deletion requests: sovereign@enlighten.mint.cafe. For legal notices, please include "PRIVACY" in the subject line. We respond within 7 business days.',
    },
  ];

  return (
    <div className="min-h-screen px-4 py-8" style={{ background: 'transparent' }} data-testid="privacy-page">
      <div className="max-w-2xl mx-auto">
        <button onClick={() => navigate(-1)} className="flex items-center gap-2 mb-6 px-3 py-2 rounded-xl active:scale-95"
          style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)', color: 'rgba(255,255,255,0.75)' }}
          data-testid="privacy-back">
          <ArrowLeft size={14} /><span className="text-xs">Back</span>
        </button>

        <h1 className="text-2xl font-bold mb-2" style={{ fontFamily: 'Cormorant Garamond, serif', color: 'rgba(248,250,252,0.85)' }} data-testid="privacy-title">
          Privacy Policy
        </h1>
        <p className="text-[11px] mb-1" style={{ color: 'rgba(255,255,255,0.6)' }}>
          ENLIGHTEN.MINT.CAFE  ·  by INFINITY SOVEREIGN
        </p>
        <p className="text-[10px] mb-8" style={{ color: 'rgba(255,255,255,0.4)' }} data-testid="privacy-updated">
          Last updated: {LAST_UPDATED}
        </p>

        <div className="space-y-4">
          {sections.map((s, i) => (
            <section key={i} className="p-4 rounded-xl" style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.05)' }} data-testid={`privacy-section-${i}`}>
              <div className="flex items-center gap-2 mb-2">
                <s.icon size={14} style={{ color: s.color }} />
                <h2 className="text-sm font-bold" style={{ color: s.color }}>{s.title}</h2>
              </div>
              <p className="text-[11px] leading-relaxed" style={{ color: 'rgba(255,255,255,0.75)' }}>{s.content}</p>
            </section>
          ))}
        </div>

        <div className="mt-8 p-4 rounded-xl" style={{ background: 'rgba(255,255,255,0.01)', border: '1px solid rgba(255,255,255,0.03)' }}>
          <p className="text-[9px] font-mono" style={{ color: 'rgba(248,250,252,0.35)' }}>
            This Privacy Policy is governed by the laws applicable to the Private Sovereign Trust that operates ENLIGHTEN.MINT.CAFE. Nothing in this document constitutes a waiver of sovereign rights or grants advertising-tracking or profiling rights to any party. By continuing to use the App, you consent to the data practices described above.
          </p>
        </div>
      </div>
    </div>
  );
}
