import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import { Loader2, Sparkles, Calendar, ChevronLeft, ChevronRight, FileText, BarChart3, Brain, Heart, BookOpen, Flame, Star, Share2, ArrowRight } from 'lucide-react';
import { toast } from 'sonner';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

function getMonthOptions() {
  const months = [];
  const now = new Date();
  for (let i = 0; i < 6; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    months.push({
      value: `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`,
      label: d.toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
    });
  }
  return months;
}

/* ─── Report Viewer ─── */
function ReportView({ report, onBack }) {
  const handleShare = async () => {
    const text = `My Soul Report for ${report.month_name}\n\n${report.report.slice(0, 200)}...\n\nGenerated by The Cosmic Collective`;
    if (navigator.share) {
      try { await navigator.share({ title: `Soul Report — ${report.month_name}`, text }); } catch {}
    } else {
      navigator.clipboard.writeText(text);
      toast.success('Report copied to clipboard');
    }
  };

  const stats = report.stats || {};

  return (
    <div className="max-w-2xl mx-auto" data-testid="report-view">
      <div className="flex items-center justify-between mb-6">
        <button onClick={onBack}
          className="flex items-center gap-1.5 text-xs transition-colors hover:opacity-80"
          style={{ color: 'var(--text-muted)' }} data-testid="report-back-btn">
          <ChevronLeft size={14} /> All Reports
        </button>
        <button onClick={handleShare} data-testid="report-share-btn"
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[10px]"
          style={{ background: 'rgba(216,180,254,0.08)', border: '1px solid rgba(216,180,254,0.15)', color: '#D8B4FE' }}>
          <Share2 size={10} /> Share
        </button>
      </div>

      {/* Header Card */}
      <div className="glass-card p-6 mb-6 relative overflow-hidden">
        <div className="absolute top-4 right-4 opacity-10">
          <Sparkles size={48} style={{ color: '#D8B4FE' }} />
        </div>
        <p className="text-[10px] font-bold uppercase tracking-[0.2em] mb-2" style={{ color: '#D8B4FE' }}>
          Soul Report
        </p>
        <h1 className="text-2xl font-light mb-1" style={{ fontFamily: 'Cormorant Garamond, serif', color: 'var(--text-primary)' }}>
          {report.month_name}
        </h1>
        <p className="text-[10px]" style={{ color: 'var(--text-muted)' }}>
          Generated {new Date(report.generated_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
        </p>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-4 gap-2 mb-6">
        {[
          { label: 'Activities', value: stats.total_activities || 0, color: '#818CF8', icon: BarChart3 },
          { label: 'Active Days', value: stats.active_days || 0, color: '#2DD4BF', icon: Calendar },
          { label: 'Mood Entries', value: stats.mood_entries || 0, color: '#FDA4AF', icon: Heart },
          { label: 'AI Sessions', value: stats.akashic_sessions || 0, color: '#38BDF8', icon: Brain },
        ].map((s, i) => (
          <div key={i} className="glass-card p-3 text-center">
            <s.icon size={12} style={{ color: s.color, margin: '0 auto 4px' }} />
            <p className="text-base font-light" style={{ fontFamily: 'Cormorant Garamond, serif', color: s.color }}>{s.value}</p>
            <p className="text-[8px]" style={{ color: 'var(--text-muted)' }}>{s.label}</p>
          </div>
        ))}
      </div>

      {/* Top Categories */}
      {stats.top_categories?.length > 0 && (
        <div className="flex flex-wrap gap-2 mb-6">
          {stats.top_categories.map((c, i) => (
            <span key={i} className="text-[10px] px-3 py-1 rounded-full"
              style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)', color: 'var(--text-muted)' }}>
              {c.category} ({c.count})
            </span>
          ))}
        </div>
      )}

      {/* Report Content — Markdown-like rendering */}
      <div className="glass-card p-6 mb-8" data-testid="report-content">
        <ReportMarkdown text={report.report} />
      </div>
    </div>
  );
}

/* ─── Simple Markdown Renderer ─── */
function ReportMarkdown({ text }) {
  const lines = text.split('\n');
  return (
    <div className="space-y-3">
      {lines.map((line, i) => {
        const trimmed = line.trim();
        if (!trimmed) return <div key={i} className="h-2" />;
        if (trimmed.startsWith('## ')) {
          return (
            <h2 key={i} className="text-sm font-semibold pt-3 pb-1 flex items-center gap-2"
              style={{ color: '#D8B4FE', borderBottom: '1px solid rgba(216,180,254,0.1)', paddingBottom: '8px' }}>
              <Sparkles size={12} /> {trimmed.slice(3)}
            </h2>
          );
        }
        if (trimmed.startsWith('# ')) {
          return (
            <h1 key={i} className="text-base font-bold pt-2" style={{ color: 'var(--text-primary)' }}>
              {trimmed.slice(2)}
            </h1>
          );
        }
        if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          return (
            <p key={i} className="text-xs leading-relaxed pl-4 flex items-start gap-2" style={{ color: 'var(--text-primary)' }}>
              <span className="inline-block w-1 h-1 rounded-full mt-1.5 flex-shrink-0" style={{ background: '#D8B4FE' }} />
              {trimmed.slice(2)}
            </p>
          );
        }
        // Bold text
        const parts = trimmed.split(/(\*\*.*?\*\*)/g);
        return (
          <p key={i} className="text-xs leading-relaxed" style={{ color: 'var(--text-primary)' }}>
            {parts.map((part, j) => {
              if (part.startsWith('**') && part.endsWith('**')) {
                return <strong key={j} style={{ color: '#D8B4FE' }}>{part.slice(2, -2)}</strong>;
              }
              return part;
            })}
          </p>
        );
      })}
    </div>
  );
}

/* ─── Main Page ─── */
export default function SoulReports() {
  const { token } = useAuth();
  const [reports, setReports] = useState([]);
  const [activeReport, setActiveReport] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [loading, setLoading] = useState(true);
  const [selectedMonth, setSelectedMonth] = useState(getMonthOptions()[0].value);
  const headers = { Authorization: `Bearer ${token}` };
  const monthOptions = getMonthOptions();

  const fetchReports = useCallback(async () => {
    try {
      const res = await axios.get(`${API}/soul-reports`, { headers });
      setReports(res.data.reports || []);
    } catch {}
    setLoading(false);
  }, [token]);

  useEffect(() => { if (token) fetchReports(); else setLoading(false); }, [token, fetchReports]);

  const generateReport = async () => {
    if (!token) { toast.error('Sign in to generate a Soul Report'); return; }
    setGenerating(true);
    try {
      const res = await axios.post(`${API}/soul-reports/generate`, { month: selectedMonth }, { headers });
      setActiveReport(res.data);
      fetchReports();
      toast.success('Soul Report generated');
    } catch (e) {
      toast.error('Could not generate report');
    }
    setGenerating(false);
  };

  const openReport = async (month) => {
    try {
      const res = await axios.get(`${API}/soul-reports/${month}`, { headers });
      setActiveReport(res.data);
    } catch {
      toast.error('Could not load report');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen immersive-page flex items-center justify-center">
        <Loader2 className="animate-spin" size={24} style={{ color: '#D8B4FE' }} />
      </div>
    );
  }

  if (!token) {
    return (
      <div className="min-h-screen flex items-center justify-center px-4">
        <div className="text-center">
          <FileText size={32} style={{ color: '#D8B4FE', margin: '0 auto 16px' }} />
          <p className="text-sm" style={{ color: 'var(--text-muted)' }}>Sign in to access your Soul Reports</p>
        </div>
      </div>
    );
  }

  if (activeReport) {
    return (
      <div className="min-h-screen px-4 pt-20 pb-24" data-testid="soul-reports-page">
        <ReportView report={activeReport} onBack={() => { setActiveReport(null); fetchReports(); }} />
      </div>
    );
  }

  return (
    <div className="min-h-screen px-4 pt-20 pb-24" data-testid="soul-reports-page">
      <div className="max-w-2xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="w-20 h-20 rounded-full mx-auto mb-4 flex items-center justify-center"
            style={{ background: 'radial-gradient(circle, rgba(216,180,254,0.15) 0%, transparent 70%)', border: '1px solid rgba(216,180,254,0.1)' }}>
            <FileText size={32} style={{ color: '#D8B4FE' }} />
          </div>
          <h1 className="text-xl font-bold mb-2" style={{ color: 'var(--text-primary)' }}>Soul Reports</h1>
          <p className="text-xs leading-relaxed max-w-md mx-auto" style={{ color: 'var(--text-muted)' }}>
            AI-generated monthly reflections on your spiritual journey — which traditions called to you, what patterns emerged, and guidance for the path ahead.
          </p>
        </div>

        {/* Generate New Report */}
        <div className="glass-card p-6 mb-8" data-testid="generate-section">
          <p className="text-xs font-semibold mb-3 flex items-center gap-2" style={{ color: 'var(--text-primary)' }}>
            <Sparkles size={14} style={{ color: '#D8B4FE' }} /> Generate a Report
          </p>
          <div className="flex gap-3 items-end">
            <div className="flex-1">
              <label className="text-[10px] block mb-1" style={{ color: 'var(--text-muted)' }}>Select Month</label>
              <select value={selectedMonth} onChange={e => setSelectedMonth(e.target.value)}
                data-testid="month-selector"
                className="w-full text-xs rounded-xl px-4 py-2.5 outline-none"
                style={{ background: 'rgba(15,17,28,0.6)', border: '1px solid rgba(216,180,254,0.12)', color: 'var(--text-primary)' }}>
                {monthOptions.map(m => (
                  <option key={m.value} value={m.value}>{m.label}</option>
                ))}
              </select>
            </div>
            <button onClick={generateReport} disabled={generating}
              data-testid="generate-report-btn"
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-xs font-medium transition-all hover:scale-[1.02]"
              style={{
                background: generating ? 'rgba(216,180,254,0.05)' : 'linear-gradient(135deg, rgba(216,180,254,0.12), rgba(129,140,248,0.1))',
                border: '1px solid rgba(216,180,254,0.2)',
                color: '#D8B4FE',
                opacity: generating ? 0.6 : 1,
              }}>
              {generating ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
              {generating ? 'Channeling...' : 'Generate'}
            </button>
          </div>
          {reports.some(r => r.month === selectedMonth) && (
            <p className="text-[10px] mt-2" style={{ color: '#2DD4BF' }}>
              A report for this month already exists — it will be shown.
            </p>
          )}
        </div>

        {/* Past Reports */}
        {reports.length > 0 ? (
          <div>
            <p className="text-xs font-semibold mb-3 flex items-center gap-2" style={{ color: 'var(--text-primary)' }}>
              <Calendar size={14} style={{ color: '#818CF8' }} /> Past Reports
            </p>
            <div className="space-y-3">
              {reports.map((r, i) => (
                <motion.button key={r.month} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05 }}
                  onClick={() => openReport(r.month)}
                  data-testid={`report-item-${r.month}`}
                  className="w-full glass-card p-5 text-left transition-all hover:scale-[1.005]">
                  <div className="flex items-center justify-between">
                    <div>
                      <h3 className="text-sm font-semibold mb-1" style={{ color: 'var(--text-primary)' }}>{r.month_name}</h3>
                      <div className="flex gap-3 text-[10px]" style={{ color: 'var(--text-muted)' }}>
                        <span>{r.stats?.total_activities || 0} activities</span>
                        <span>{r.stats?.active_days || 0} active days</span>
                        <span>Generated {new Date(r.generated_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span>
                      </div>
                    </div>
                    <ArrowRight size={14} style={{ color: '#D8B4FE' }} />
                  </div>
                </motion.button>
              ))}
            </div>
          </div>
        ) : (
          <div className="text-center py-8">
            <p className="text-xs" style={{ color: 'var(--text-muted)' }}>No reports yet. Generate your first Soul Report above.</p>
          </div>
        )}
      </div>
    </div>
  );
}
